name: my_favorite_places
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  path: ^1.8.0
  sqflite: ^2.0.2
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
